course:
    name: HFOSS
    desc: The RIT Humanitarian Free/Open Source Software Development Course
    place: RIT
    start: 2015-08-25
    end: 2015-12-10
    blog_start: 2015-09-08
    blog_end: 2015-12-20
    times: Mon & Wed 5:00PM - 6:15PM
    course: 4085.582.01
    location: Orange Hall (ORN)-1375
    final: 5/20, 5:00PM-7:00pm, ORN-1375
    repo: http://github.com/ritjoe/hfoss
    public_url: http://hfoss-ritigm.rhcloud.com

instructor:
    name: D. Joe Anderson
    email: deejoe@mail.rit.edu
    irc: dzho
    avatar: None
    openhub: None
    twitter: deej0e
    office:
        location: The MAGIC Center - SIH 1680
        hours: Monday, Wednesday, 4:00-5:00pm
    links:
        blog: None
        linkedin: None
        github: http://github.com/ritjoe
        opensource: None

assistant:
    name: Mike Nolan (Nolski)
    email: me@michael-nolan.com
    irc: Nolski

